### ISSUE TITLE
Settings checkboxes are no longer clickable

### ISSUE THREAD

**Issue by Tomcraft1980** [thoukydides/homebridge-aeg-robot#54]
### Description of Issue

Somehow the checkboxes in the settings are no longer clickable.
The last things I did was:
- Activate the debug options in the plugin and activate the -D switch in homebridge settings.
- Deactivate -D switch in homebridge settings.
- Update the plugin from 2.0.0 to 2.1.0
Unchecking another yet activated checkbox works, but it is not possible to check it again afterwards.

Tested with FireFox 132.0b4 & Safari 18.0.1
Even the downgrade to plugin version 2.0.0 does not make the checkboxes clickable.

### Plugin Version

2.1.0

### Diagnostic Checks

- [ ] AEG iPhone app is able to control the appliance.

**Comment by thoukydides** [comment]
They work fine for me in:
- Chrome Version 129.0.6668.90 (Official Build) (64-bit) on Windows 11.
- Safari on iOS 18.0.1.

Do checkboxes work in the configurations for other plugins?

The configuration is just provided as a JSON schema. It is [Homebridge UI](https://github.com/homebridge/homebridge-config-ui-x) that renders it into a webpage. If there is an issue then it will be with that plugin, not this one.

**Comment by Tomcraft1980** [comment]
I just updated homebridge from 1.3.6 to 1.3.7 and then it worked just fine.
After that I got noticed about homebridge-config-ui-x update from 4.59.0 to 4.60.1 again.
And that seems to be responsible for the problem.

**Comment by Tomcraft1980** [comment]
> Also, you say that the problem persists with older versions of this plugin which previously worked for you.

I think this was before updating to homebridge-config-ui-x 4.60.1

I will try to uninstall the plugin and delete the config and then reinstall.

**Comment by thoukydides** [comment]
Having just cleared my browser crashes I can now see the issue with the checkboxes in [Homebridge UI](https://github.com/homebridge/homebridge-config-ui-x). It appears to affect all plugins that use a static `config.schema.json`, but not those that use a custom UI via [homebridge/plugin-ui-utils](https://github.com/homebridge/plugin-ui-utils). Hence, this is definitely a problem with [homebridge-config-ui-x](https://github.com/homebridge/homebridge-config-ui-x) rather than this plugin.

**Comment by Tomcraft1980** [comment]
Ah great! Can you (as a plugin developer) report this issue to [homebridge-config-ui-x](https://github.com/homebridge/homebridge-config-ui-x)?

**Comment by thoukydides** [comment]
This is fixed in homebridge-config-ui-x [4.60.2-beta.1](https://www.npmjs.com/package/homebridge-config-ui-x/v/4.60.2-beta.1).

See homebridge/homebridge-config-ui-x#2200 and homebridge/homebridge-config-ui-x@09be61beb0d142836cfecf488b266538213f1ea3.

**Comment by Tomcraft1980** [comment]
Cool, thanks for the info!
